// This file is auto-generated by TanStack Router. Do not edit this file manually.
import { createRoute } from '@tanstack/react-router'
import { Route as rootRoute } from './routes/__root'
import { UtilitiesPage } from './features/utility-dashboard/overview'
import { ElectricityPage } from './features/utility-dashboard/electricity'
import { InternetPage } from './features/utility-dashboard/internet'
import { MobileMoneyPage } from './features/utility-dashboard/mobile-money'
import { SettingsPage } from './features/utility-dashboard/settings'
import { WaterPage } from './features/utility-dashboard/water'

const utilityRoute = createRoute({
	getParentRoute: () => rootRoute,
	path: '/utility',
	component: UtilitiesPage,
})

const utilityTree = utilityRoute.addChildren([
	createRoute({ getParentRoute: () => utilityRoute, path: '/electricity', component: ElectricityPage }),
	createRoute({ getParentRoute: () => utilityRoute, path: '/internet', component: InternetPage }),
	createRoute({ getParentRoute: () => utilityRoute, path: '/mobile-money', component: MobileMoneyPage }),
	createRoute({ getParentRoute: () => utilityRoute, path: '/settings', component: SettingsPage }),
	createRoute({ getParentRoute: () => utilityRoute, path: '/water', component: WaterPage }),
])

export const routeTree = rootRoute.addChildren([utilityTree])
